# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d94c0b823ebd49e4e60306be11f0d79d520af6f3f9f1594b3f01248b06b25777d2404fe19449702b8a6ccba06bbc0823679e6eb0541c491398330ba2b19f1fd4

test:
  secret_key_base: 160b5c3539a1fc7aab8f3a17333d5f7f2e5c3b0d6562d9224e48d0c0357f09dfd9db47cf22dc7fdfe749e37b5df87676e743c5e7152f417caf1cc2a5e7695c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
